### ISSUE TITLE
Demo中 调用applyState()时会导致显示的文字每次少一个字符

### ISSUE THREAD

**Issue by MAIMIHO** [timqi/CollapsibleTextView#1]
作者你好, 请问
applyState(boolean expanded)中
`int newEnd = lineEnd - suffix.length() - 1;`
后面再 -1 是为什么呢? 

Demo中 调用applyState()时会导致显示的文字每次少一个字符

**Comment by timqi** [comment]
英文通常不是等宽字体以及分词显示等原因，根据字符数判断可能会有行益出，这个地方应该根据使用场景选择更可靠判断行数的方法
